### ISSUE TITLE
Can't get to UI signup

### ISSUE THREAD

**Issue by Mark2M** [edgedb/edgedb-js#1002]
I enabled authentication etc., configured smtp but when I load the signup page I just get an error stating "missing challenge in register request, type invalid data. I get similar errors for the signing url and the callback url.

cheers

**Comment by scotttrinh** [comment]
Are you using one of the helper libraries?

**Comment by Mark2M** [comment]
Nothing other than the edge api etc. I enabled auth, set up the provider etc. in the ui and that was pretty much it...

**Comment by krambs** [comment]
How did you resolve this? Thanks!

**Comment by Mark2M** [comment]
I didn't... I scrapped the code. I was only experimenting and ran out of time...
