### ISSUE TITLE
Shape with pointer of `false` produces type suggesting the pointer is returned

### ISSUE THREAD

**Issue by CarsonF** [edgedb/edgedb-js#1037]
```typescript
e.select(e.X, {
  foo: false
})
```
Runtime omits `foo` from EdgeQL, but TS types it as `never`.
This allows it to be compatible, somehow, with a type expecting that property.

```typescript
class X {
  foo: string;
}
const withX = (x: X) => {...};

const result = await e.select(e.X, {
  foo: false
}).run();

// This is fine even though `foo` is required, and not in the DB result.
withX(result[0]);
```

I think the type should be changed to `undefined`, or maybe `unknown` instead?

**Comment by CarsonF** [comment]
Could we change the arg shape to reject `false`?
https://github.com/edgedb/edgedb-js/blob/0bf404ec6e3479379417b234e0500e2f4b76310d/packages/generate/src/syntax/select.ts#L755-L755
```ts
| true
```

**Comment by diksipav** [comment]
We fixed this issue with first @scotttrinh recommendation above. We don't return anymore "these keys" in the resulting objects.
