### ISSUE TITLE
resolveConnectionParams listing incorrect source for database/branch

### ISSUE THREAD

**Issue by mfenn** [edgedb/edgedb-js#1069]
**Describe the bug**
`resolveConnectionParams` seems to erroneously report the source of a branch as "default" when the `EDGEDB_BRANCH` env variable is used, though the branch specified by `EDGEDB_BRANCH` **is** correctly used.

**Reproduction**
We use `resolveConnectionParams` to log connection parameters when our application starts up. I ran with the `EDGEDB_INSTANCE` and `EDGEDB_BRANCH=example` (but not the default `main`).

```
Parameter          Value                                    Source
---------          -----                                    ------
host               <host>                                    'EDGEDB_INSTANCE' environment variable
port               5656                                      'EDGEDB_INSTANCE' environment variable
database           example (default)                         default
...
```

**Expected behavior**
I would expect that it would report the source of the branch as the `'EDGEDB_BRANCH' environment variable`.

**Versions (please complete the following information):**

- OS: macOS 14.5
- EdgeDB version (e.g. `2.0`): `5.3+7adaf21`
- EdgeDB CLI version (e.g. `2.0`): `5.2.2+ed96c17`
- `edgedb-js` version (e.g. `0.20.10`): `1.5.8`
- Node/Deno version: `Node v22.4.1`

**Comment by scotttrinh** [comment]
Does the `branch` parameter show the correct branch here?

**Comment by scotttrinh** [comment]
Hmmm, it _should_ be there via: https://github.com/edgedb/edgedb-js/blob/9c60b14e2b0ab55f2b81e36027a2ba0707a7142f/packages/driver/src/conUtils.ts#L358-L360

Oh! Maybe you're using `explainConfig()` https://github.com/edgedb/edgedb-js/blob/9c60b14e2b0ab55f2b81e36027a2ba0707a7142f/packages/driver/src/conUtils.ts#L390

It is indeed missing from that table. Will fix.

**Comment by mfenn** [comment]
Oh yeah, sorry, should have been more clear.

**Comment by scotttrinh** [comment]
> Oh yeah, sorry, should have been more clear.

No problem! Should be fixed up in just a few minutes.

**Comment by scotttrinh** [comment]
@mfenn 

Can you try the latest canary (https://www.npmjs.com/package/edgedb/v/1.6.0-canary.20240730T180738) and let me know if it works for you? If so, I'll publish a patch release.

**Comment by mfenn** [comment]
Yep, looks good. Is there any difference between database and branch at this point?

**Comment by scotttrinh** [comment]
@mfenn 

> Is there any difference between database and branch at this point?

"Branch" is a superset of "database". It has a few more features (like being able to copy data when creating a new branch, and some CLI commands) but from a purely data/connection perspective, branch supersedes database as a concept.
