### ISSUE TITLE
Query builder is returning default global scalar type instead of what is set

### ISSUE THREAD

**Issue by luveshsadhwani** [edgedb/edgedb-js#1093]
**Describe the bug**
The query builder returns the default value of the global scalar type rather than what is set

**Reproduction**
1. Set schema in `default.esdl`
```
module default {
    scalar type Mode extending enum<Info, Debug>;
    
    required global tester_mode: Mode {
          default := Mode.Info;
    }
```

2. Set up script
```typescript
import createClient from "edgedb";
const client = createClient();

const query = e.select(e.global.tester_mode) // tried with e.global.tester_mode as well;
const result = await query.run(client);
console.log(JSON.stringify(result, null, 2))
```
3. Run script
```
"Info"
```
4. Connect to EdgeDB local instance
5. Update `tester_mode`
```
easy_edgedb:main> set global tester_mode := Mode.Debug;
OK: SET GLOBAL
```
6. Check that `tester_mode` has been updated
```
easy_edgedb:main> select global tester_mode
{Debug}
```
7. Run script in 2 again
```
"Info"
```
8. Update schema to set default value of `tester_mode` to `Mode.Debug`
9. Update `default.esdl`
```
required global tester_mode: Mode {
    default := Mode.Debug;
}
```
10. Run migration
```
easy_edgedb:main> \migration create
did you alter global 'default::tester_mode'? [y,n,l,c,b,s,q,?]
> y
Created file-1.edgeql, id: M-ID
easy_edgedb:main> \migrate
Applying M-ID (file-1.edgeql)
... parsed
... applied
```
11. Run script in 2 again
```
"Debug"
```

**Expected behavior**
We should see the updated global value if the value has been changed.

**Versions (please complete the following information):**

- OS: `MacOS 14.3.1`
- EdgeDB version (e.g. `2.0`): `5.6+adb9e77`
- EdgeDB CLI version (e.g. `2.0`): `5.2.3+4559649`
- `edgedb-js` version (e.g. `0.20.10`;): `1.5.11`
- ~~Node/Deno~~ Bun version: 1.0.8

**Additional context**
None

**Comment by scotttrinh** [comment]
Globals are set per-request (really, per session, but for client usage this is the same thing), so you would set the global like:

```ts
const client = createClient();
const clientWithGlobal = client.withGlobals({
  tester_mode: e.Mode.Debug,
});
const query = e.select(e.global.tester_mode) // tried with e.global.tester_mode as well;
const result = await query.run(client);
console.log(JSON.stringify(result, null, 2))
// should print "Debug"
```

**Comment by scotttrinh** [comment]
In other words, the value of the global is not something that is _in_ the database (as in, it's not persisted in the database), but rather something that is part of the client state when you're making queries. For CLI REPL usage, you use `set global` which modifies that REPL client's state for the duration of the REPL session. For client libraries (like the TS query builder), you set is as part of the client using `withGlobals`.

See:
- https://docs.edgedb.com/database/datamodel/globals#setting-global-variables
   > Global variables are set when initializing a client.
- https://docs.edgedb.com/libraries/js/reference#Client.withGlobals
   > Returns a new Client instance with the specified global values. The globals argument object is merged with any existing globals defined on the current client instance.
   > Equivalent to using the set global command.

**Comment by luveshsadhwani** [comment]
@scotttrinh That makes sense, thank you for the explanation 👍 

FYI, I got an error for not passing a string to `tester_mode` with `e.Mode.Debug`, rather I used `e.Mode.Debug.__value__`

**Comment by scotttrinh** [comment]
> FYI, I got an error for not passing a string to tester_mode with e.Mode.Debug, rather I used e.Mode.Debug.__value__

Oh, that's a good catch. I think that's something we should support since we don't want users to have to know about so-called dunder properties, and treat literals like that as interchangeable with the string literals they represent. Thanks for following up there, I'm sure that'll be helpful for others, and we'll look into getting enum literals working like that.

**Comment by luveshsadhwani** [comment]
Awesome, looking forward to that 🥳
