### ISSUE TITLE
createPool options typings

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb-js#162]
Typescript complains about this when specifying connection option `database` in `createPool` even though it actually works.

```
Argument of type '{ database: string; }' is not assignable to parameter of type 'PoolOptions'.
  Object literal may only specify known properties, and 'database' does not exist in type 'PoolOptions'.
```

**Comment by jaclarke** [comment]
There isn't a `database` option in the pool options, it should be passed to `connectOptions` in the `PoolOptions` object:
```js
createPool('instance-or-dsn', {
  connectOptions: {
    database: 'database-name'
  }
})
```

**Comment by haikyuu** [comment]
Thanks @jaclarke
