### ISSUE TITLE
`Failed to resolve import "edgedb.js"` when targeting esm

### ISSUE THREAD

**Issue by pheuter** [edgedb/edgedb-js#235]
```bash
npx edgeql-js --target esm
svelte-kit dev
```

```
10:22:44 AM [vite] Error when evaluating SSR module /Users/mark/src/Careswitch/platform/src/routes/index.ts:
Error: Failed to resolve import "edgedb.js" from "dbschema/edgeql-js/index.mjs". Does the file exist?
```

If I manually go into `dbschema/edgeql-js/index.mjs` and do the following replace everything appears to work as expected:

```js
// Old
export { createClient } from "edgedb.js";

// New
export { createClient } from "edgedb";
```

**Comment by colinhacks** [comment]
Yep, good catch. Looking into a fix now.

**Comment by NexZhu** [comment]
@colinhacks In the `--target esm` output, generated `.mjs` files are using corrcect import path with file suffix '.mjs' but `.d.ts` files are not, `.d.ts` files are still using CommonJS format import paths (no `.js/.mjs` suffix).

**Comment by raddevon** [comment]
Mentioning @jaclarke since he's currently maintaining this project.
