### ISSUE TITLE
Typing inference wrong on inserts

### ISSUE THREAD

**Issue by busheezy** [edgedb/edgedb-js#242]
It seems that an insert is showing as a type of many. This makes it impossible to chain with a conflict else.

The error:
``the query has cardinality MANY which does not match the expected cardinality ONE``

https://github.com/busheezy/edgedb-upsert-type-inference-error/blob/main/src/index.ts#L9
I have made an example repo. You can run ``npm run rebuild:db`` to create everything.

https://share.busheezy.dev/wrlepR.png

Thanks to @elprans for the quick reply on discord.

Thanks for the cool new toys!

**Comment by colinhacks** [comment]
Good catch, we'll push some fixes by the end of today!

**Comment by colinhacks** [comment]
Fixed in 0.19.2 👍
