### ISSUE TITLE
Add `.index` method to tuple expressions

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb-js#250]
```ts
const tuple = e.tuple([
  e.str("Peter Parker"),
  e.int64(18)
]);
tuple[0];   // works
tuple.index(0);    // not implemented
```

**Comment by jaclarke** [comment]
Why do we need a `.index` method on tuples? The only values it could take are the same `0`, `1`, etc... that the brackets syntax allows, so it seems kind of redundant. (Unlike the `.index` method on arrays, where it can also take an expression that the brackets syntax can't).

**Comment by elprans** [comment]
Yes.  `index()` implies you can use an expression, but you can't, so it isn't exactly consistent with array indexing.
