### ISSUE TITLE
Array type errors

### ISSUE THREAD

**Issue by bavellone** [edgedb/edgedb-js#260]
Using the latest v0.19.5 with the following minimal schema:
```
module default {
  type App {
    required property nicknames -> array<str>;
  }
}
```

According to the [docs](https://www.edgedb.com/docs/clients/01_js/literals#arrays), arrays can accept plain JS data but I'm getting type errors when passing a variable:
```js

// Works
const app = e.insert(e.App, {
  nicknames: e.array(['one', 'two'])
})

// Throwing errors on `nicknames` and `e.array(names)`
const names = ['one', 'two']
const app = e.insert(e.App, {
  nicknames: e.array(names)
})
```
First error
```
(property) nicknames: {
    __element__: ArrayType<$str, "array<std::str>">;
    __cardinality__: Cardinality.One;
}
Property '__cardinality__' is missing in type 'ArrayType<CastableNonArrayType, `array<${string}>`>' but required in type '{ __element__: ArrayType<$str, "array<std::str>">; __cardinality__: Cardinality.One; }'
```
Second error
```
No overload matches this call.
  Overload 1 of 2, '(element: CastableNonArrayType): ArrayType<CastableNonArrayType, `array<${string}>`>', gave the following error.
    Argument of type 'string[]' is not assignable to parameter of type 'CastableNonArrayType'.
      Type 'string[]' is missing the following properties from type 'NamedTupleType<NamedTupleShape>': __name__, __kind__, __shape__
  Overload 2 of 2, '(arg: [string, ...string[]]): $expr_Array<ArrayType<ScalarType<"std::str", string, true, string>, "array<std::str>">, never>', gave the following error.
    Argument of type 'string[]' is not assignable to parameter of type '[string, ...string[]]'.
      Source provides no match for required element at position 0 in target.
```

**Comment by colinhacks** [comment]
While this should work, you can solve this problem by just dropping `e.array`:

```ts
const names = ['one', 'two']
const app = e.insert(e.App, {
  nicknames: names
})
```

When we say you can pass in raw data, we really mean it :)

The error causes when you use `e.array` is a tricky one. Basically we intentionally infer the input of `e.array` as a tuple, which lets us do intelligent things like infer the cardinality of the final array by multiplying the cardinalities of each element. The downside is that passing in anything with a `something[]` type signature fails...we'll keep thinking about this. For now just drop `e.array` and you should be good.

**Comment by bavellone** [comment]
Excellent! This works:
```js
const nicknames = e.literal(e.array(e.str), ['one', 'two'])
const app = e.insert(e.App, {
  nicknames
})
```
But I'm seeing an error with the example you provided on 0.19.6:
```js
const names = ['one', 'two']
const app = e.insert(e.App, {
  nicknames: names
})

(property) nicknames: {
    __element__: ArrayType<$str, "array<std::str>">;
    __cardinality__: Cardinality.One;
}
Type 'string[]' is missing the following properties from type '{ __element__: ArrayType<$str, "array<std::str>">; __cardinality__: Cardinality.One; }': __element__, __cardinality__
```

Testing out some more variations, it looks like I'm getting the same error above for this as well:
```js
const app = e.insert(e.App, {
  nicknames: ['one', 'two']
})
```

As long as I can insert dynamic arrays I'm a happy camper so the literal method works for me for now. Very eager to prototype with EdgeDB and loving it so far although more detailed docs and complex examples would be great!

**Comment by bavellone** [comment]
Excellent! This works:
```js
const nicknames = e.literal(e.array(e.str), ['one', 'two'])
const app = e.insert(e.App, {
  nicknames
})
```
But I'm seeing an error with the example you provided on 0.19.6:
```js
const names = ['one', 'two']
const app = e.insert(e.App, {
  nicknames: names
})

(property) nicknames: {
    __element__: ArrayType<$str, "array<std::str>">;
    __cardinality__: Cardinality.One;
}
Type 'string[]' is missing the following properties from type '{ __element__: ArrayType<$str, "array<std::str>">; __cardinality__: Cardinality.One; }': __element__, __cardinality__
```

Testing out some more variations, it looks like I'm getting the same error above for this as well:
```js
const app = e.insert(e.App, {
  nicknames: ['one', 'two']
})
```

As long as I can insert dynamic arrays I'm a happy camper so the literal method works for me for now. Very eager to prototype with EdgeDB and loving it so far although more detailed docs and complex examples would be great!
