### ISSUE TITLE
Are arrays valid values in query arguments?

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb-js#27]
I'm trying to run a query that contains a set as an argument, for example:
``` js
await conn.fetchAll(`
  # This query works
  SELECT schema::ObjectType { id, name }
  FILTER .id IN <uuid>{
    '00000000-0000-0000-0000-000000000001',
    '00000000-0000-0000-0000-000000000002'
  };
  # Replacing the filter expression to use a query argument (as either below) doesn't work
  # FILTER .id IN <uuid>$tids
  # FILTER .id IN <uuid>{$tids}
`, {
    tids: ['00000000-0000-0000-0000-000000000001',
           '00000000-0000-0000-0000-000000000002']
  }
)
```
Are arrays not accepted as query argument values (the examples in the docs only show scalar types), or this not the correct syntax?

**Comment by elprans** [comment]
The correct syntax for an array cast is `<array<uuid>>$tids`.

**Comment by elprans** [comment]
Oh, and you will also need to use `array_unpack` to convert the array to a set:

`FILTER .id IN array_unpack(<array<uuid>>$tids)`

**Comment by jaclarke** [comment]
Thanks, that works.
