### ISSUE TITLE
List of reserved words for property names

### ISSUE THREAD

**Issue by eugene1g** [edgedb/edgedb-js#291]
Hi,

The docs [mention](https://github.com/edgedb/edgedb-js/blob/master/docs/select.rst#filtering) that `filter` is a reserved word, and we should not have a property with the same name. Two questions - 

1. Is there a list of all other reserved words that we should avoid in our schema? 
2. Is there a long-term strategy for how EdgeDB might introduce new reserved words? For example, using a naming convention like `:filter` or `filter$`.

For the current list, I found this - 
https://github.com/edgedb/edgedb-js/blob/ffd46a12021679f220c1767c9bc9d40882c8d1c1/src/syntax/select.ts#L84-L98

**Comment by colinhacks** [comment]
Here "reserved keyword" means it's reserved by EdgeQL, not just the query builder. You can see the full list here: https://www.edgedb.com/docs/reference/edgeql/lexical

**Comment by colinhacks** [comment]
2. EdgeDB is unlikely to introduce any additional reserved keywords in the near future. We've already pre-reserved all the keywords we'll need for EdgeDB v2.x. Beyond that we *may* reserve more but it probably won't affect the query builder.

**Comment by eugene1g** [comment]
Excellent, thank you!
