### ISSUE TITLE
Get parsed json for json type

### ISSUE THREAD

**Issue by hlehmann** [edgedb/edgedb-js#338]
### Problem:
Is there a particular reason to retrieve `json` data as a javascript `string` instead of its parsed value ?

Some data are unshaped so I set them in a json. But this data is still useful, and I would like to read it, currently I have to run the query then go through my data, do the parsing and change the types.

One of the main avantage of edgedb is that we don't need to use mapping nor an orm, having to do this breaks this logic.

### Proposal:

It would be nicer if the query could know what's intended, for example a `<json>` return a parsed json and a `<str>` gives the stringify json. Like what seems to be the case for the graphql client: `<json>` are not stringified.

The client could use to_json or to_str if he wants to change the result.

**Comment by colinhacks** [comment]
I like the idea auto automatically `JSON.parse`ing `json` fields. It's not common in the JS ecosystem for the term "JSON" to apply to a JSON-encoded string. We kinda do the same thing in reverse for `e.json` params, where we accept any JS data structure and serialize it for the user. Makes sense to do the opposite. And if a user wants a fully JSON-encoded string result they can always use `.runJSON`. thoughts @1st1 @jaclarke

**Comment by liron00** [comment]
I know there are some cases where `JSON.stringify(JSON.parse(myJsonString)) !== myJsonString`, e.g. when JSON has a numeric value that can't fit in a float, but I still think getting the JSON.parse() version is a good default applicable to 98% of use cases.

**Comment by hlehmann** [comment]
Any chance to see this soon ? From what I see for the rare people willing to get the stringify version they always can cast the value to string.

**Comment by hlehmann** [comment]
Closing it as it been implemented in 0.21. Thx!
