### ISSUE TITLE
RFC: Simplified filtering API

### ISSUE THREAD

**Issue by colinhacks** [edgedb/edgedb-js#347]
A proposal for simplified `filter` syntax for _equality filters_. The goal is to expand the scope of cardinality inference and provide a less verbose alternative to `e.op(x, "=", y)` when specifying simple equality filters.

In `e.select`, the `filter` key should also accept a plain JS object. The keys can correspond to an property/link name and can point to singleton expressions or plain JS literals.

### Current syntax

```typescript
e.select(e.Movie, (movie) => ({
  filter: e.op(movie.release_year, '=', '2008'),
}));
```

### Proposed syntax

```typescript
e.select(e.Movie, () => ({
  filter: {release_year: 1999},
}))
```

It's no longer necessary to include a reference to the scope variable ``movie`` or write the `e.op()` expression, which is one of the bits of query builder syntax that is hardest to type quickly and least conducive to autocompletion.

Type inference still works as expected. Filtering on a non-exclusive property returns an array:

```typescript
e.select(e.Movie, (movie) => ({
  title: true,
  filter: {release_year: 1999},
})).run(client);
// {title: string}[]
```

If a referenced property/link has an exclusive constraint, the result will be a singleton.

```typescript
e.select(e.Movie, (movie) => ({
  title: true,
  filter: {id: e.uuid('2053a8b4-49b1-437a-84c8-e1b0291ccd9f')},
}));
// {title: string}
```

This hold true for object-level exclusive constraints corresponding to a tuple of properties. (This is infeasible to implement using the `e.op` formulation.) e.g. if there is a compound constraint on `(.title, .release_year)` the following would be inferred to be a singleton.

```typescript
// singleton
e.select(e.Movie, (movie) => ({
  title: true,
  filter: {
    title: "A Star is Born"
    release_year: 2018
  }
}));
// {title: string}
```

An additional proposal is to support cardinality inference for "expression constraints". e.g.

```
type Movie {
  property title -> str;
  constraint exclusive on str_lower(.title);
}
```

The constraint's stored `expr` would be introspected to support the following:

```typescript
// singleton
e.select(e.Movie, (movie) => ({
  title: true,
  filter: {
    'str_lower(.title)': 'a star is born',
  },
}));
```

### Non-exclusive
 
There is a question of whether the "object filter" syntax would support non-exclusive properties. @elprans objected to supporting this syntax exclusively for singleton/exclusive filtering. Filtering by equality on an exclusive vs nonexclusive property would look very different and possibly lead to confusion.

```ts
e.select(e.Movie, (,)=>({
  filter: { id: "adsf" }
  filter: e.op(m.rating, '=', 5),
}));
```

This proposal can be generalized to a way to specify any set of equality filters (https://github.com/edgedb/edgedb-js/issues/347)

```ts
e.select(e.Movie, ()=>({
  filter: { rating: 5 }  // non-exclusive prop
}));
```

This fixes the inconsistency, but makes it less visually obvious when a `filter` clause corresponds to a singleton filter. It also increases implementation complexity, since we'll need to statically determine whether keys of the "object filter" object correspond to an exclusive constraint, instead of simply checking if the value passed to `filter` is an object literal.

**Comment by liron00** [comment]
Related as a further syntactic sugar: https://github.com/edgedb/edgedb/issues/3810#issuecomment-1119942917

When writing a subquery select-by-id, it would be great if we had an even more compact syntax to refer to the linked entity by its ID without spelling out the query.

**Comment by lodisy** [comment]
What about other operators?

Personally, I prefer something close to Graphql's style:

```typescript

FROM: filter: e.op(left, '>', right)

TO: filter: {left: {gt: right}}

FROM: filter: e.op(left, 'or', right)

TO: filter: {or: [left, right]}

...

```

**Comment by 1st1** [comment]
How would you combine new syntax and old if you have a bunch of eq filters and one non-eq? Would this be possible:

```
e.select(e.Movie, (movie) => ({
  title: true,
  filter: e.op({
    title: "A Star is Born"
    release_year: 2018
  }, 'and', e.op(movie.blah, '>', 10))
}));

```
?


Also, do we have to use `e.uuid()`? Can we allow ID types to accept string literals directly? The casting seems a bit too verbose and not super necessary.

**Comment by colinhacks** [comment]
> Personally, I prefer something close to Graphql's style:

I don't hate this, it's familiar to people and has better autocompletion than `e.op`. It also breaks composability expressions cleanly and requires several levels of object nesting, which I don't love. It's certainly on the table, but it's a separate discussion.


> How would you combine new syntax and old if you have a bunch of eq filters and one non-eq? Would this be possible:

This syntax wouldn't be allowed under the current proposal since I'm not planning to overload `e.op` to accept these "filter objects". This is merely an extension to what can be passed into the `filter` expression in a select/update/delete. Previously you could only pass a boolean expression, now you can pass either a boolean expression or this special-case "object filter". I also don't think it's important for this syntax to be composable in `e.op` since it'll almost exclusively be used in conjunction with `id` or exclusive properties. 

> do we have to use e.uuid()?

I'm very down to accept plain strings here. I think we were requiring `e.uuid` to stay as close as possible to EdgeQL, but I think this adds more confusion that it's worth.
--------

Both of these points make me think that my original proposal will be easier to explain/understand, namely that this "object filter" syntax should only work for exclusive properties or tuples. @elprans argued in favor of expanding this syntax to include all properties. Personally I think its a more satisfying DX to have a special syntax for uniquely specifying a single object. It's makes it visually obvious that you are selecting a single object, without the need for a special `.selectOne` method or `filterSingle` key. 

Expanding this syntax to include all properties invites additional questions, like "How do I use other operators?"

**Comment by colinhacks** [comment]
> do we have to use e.uuid()? Can we allow ID types to accept string literals directly? The casting seems a bit too verbose and not super necessary

We are doing this currently because we're being conservative and trying to keep the query builder semantics as close as possible to EdgeQL. Personally I agree this causes more confusion that it's worth.

**Comment by liron00** [comment]
String IDs without `e.uuid` seems good IMO, might just want to clarify the deal with the string allowed to have / not have dashes

**Comment by NetOpWibby** [comment]
Is there something blocking this from getting into EdgeDB?

**Comment by scotttrinh** [comment]
Implemented in the query builder: https://www.edgedb.com/docs/clients/js/querybuilder#select-a-single-object
