### ISSUE TITLE
Deno example

### ISSUE THREAD

**Issue by brielov** [edgedb/edgedb-js#366]
Simply wondering how to use query builder with deno without the need of having `npx` available in the environment. 

Is there any documentation on how to use it with deno?

**Comment by aarongeorge** [comment]
Looking for information on this too, trying to utilise the query builder when using Deno just doesn't seem to work. 

The query builder seems to be node specific currently.

@jaclarke is there any formal documentation around QB with Deno? If not are there any work arounds to get this working?

Thanks a lot
