### ISSUE TITLE
Set db to use

### ISSUE THREAD

**Issue by gsouf** [edgedb/edgedb-js#39]
Hello, according to [this documention](https://edgedb.com/docs/tutorial/createdb/) we should use the following command to change the current db:

```
\c tutorial
```

However I cannot find how to change the current db with the JS client without create a new connection.

I came up with this but it complains that \ is not expected:

````
const EdgeClient = require('./EdgeClient');
let c = new EdgeClient({
  user: 'edgedb',
  host: '127.0.0.1',
});
c.getConnection().then((c) => {
  const r = c.execute(`\\c tutorial`).then((r) => {
    console.log(r);
  });
});
```

Thanks

**Comment by elprans** [comment]
`\c` is a special command interpreted by REPL, it's not a server command.  Opening a new connection is *the* way to connect to a database, there's no other way.
