### ISSUE TITLE
Object['*'] does not include optional links - query builder

### ISSUE THREAD

**Issue by lu-zen** [edgedb/edgedb-js#394]
**Describe the bug**
The select shorthand `Object[*]` does not include optional links/backlinks.

**Reproduction**
Given a object:
```
type Avatar {
  required property url -> str;
  link owner := .<account[is User];
  link metadata -> AvatarMetadata;
}
```
Generate the query builder: `npx edgeql-js`;

The shorthand will be generated without the optional links;
```typescript
e.Avatar['*'];
// { id: true, url: true }
```

**Expected behavior**
All properties to be present including optional ones (regular properties are included);
```typescript
e.Avatar['*'];
// { id: true, url: true, metadata: true, owner: true }
```

**Versions**
 - OS: Linux lts
 - EdgeDB version: `2.0-rc.2+4a86481`
 - edgedb-js version: `0.21.0-beta.0`

**Additional context**
[Docs - js lib - Selecting all properties](https://www.edgedb.com/docs/clients/01_js/select#selecting-all-properties)

**Comment by colinhacks** [comment]
Keep in mind that properties and links are distinct concepts. The special `*` shorthand only includes the *properties* of the object type, not links. This is to encourage users to be more conservative when fetching links, since its a more expensive operation than selecting properties.
