### ISSUE TITLE
Running test doesn't seem to work

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb-js#40]
I'm running the latest Nightly version on Ubuntu 18

Running tests doesn't seem to be working. Is there something i need to configure before running tests?

I already have edgedb installed.

**Comment by 1st1** [comment]
Tests pass on my machine for the latest checkout of edgedb & edgedb-js repos.

Can you please elaborate on how exactly it's not working?  I've a few theories:

1. The `client.test.ts` test suite takes about 30 seconds to complete, so it doesn't output anything for a long time.

2. You need to make sure you've built the latest master -- by `git pull && git submodule update && make`; the `make` can also be replaced with `pip install -e .[test]`.

**Comment by 1st1** [comment]
Please update the issue if tests don't run on your machine with more details and we'll reopen.
