### ISSUE TITLE
Connecting to a starting EdgeDB server will stop without throwing

### ISSUE THREAD

**Issue by gsouf** [edgedb/edgedb-js#41]
### Steps to reproduce:

1. Create a js script that connects to EdgeDB:

```
const edgedb = require('edgedb');

async function main() {
  try {
    let c = await edgedb.connect({
      user: 'edgedb',
      host: '127.0.0.1',
    });
    console.log('connected');
  } catch (e) {
    console.error('caught', e);
  }
}

main();
```

2. Launch edgedb server (I used docker version).
3. Run the js script above before the server is fully launched

### Actual result

Script stops

### Expected result

An error should be caught

**Comment by haikyuu** [comment]
Same thing happens for me. Although the server is completely up and running.

I'm running an Edgedb server in AWS.

I'm using version `0.7.4` of `edgedb-js` with Edgedb `edgedb-server-1-alpha3`

**Comment by 1st1** [comment]
> Same thing happens for me. Although the server is completely up and running.

Is this a new thing or some regression?

**Comment by 1st1** [comment]
@gsouf 

>     Create a js script that connects to EdgeDB:

Thanks for reporting this, I'll take a look. What's the nodejs version you're using?

**Comment by agritheory** [comment]
This issue has also been discussed here: https://spectrum.chat/edgedb/general/a-way-to-wait-until-database-is-ready~0a96b827-26a1-4207-9f46-16cab8ac0068

I don't think this 'wait until it's ready' implementation has made it through to the clients but has been implemented in the CLI: https://github.com/edgedb/edgedb-cli/issues/4

**Comment by 1st1** [comment]
Generally speaking, I don't think that "wait until ready" should be the default behavior, but the driver must shutdown cleanly with an error if it cannot connect to the DB. The "Script stops" behavior needs to be investigated.

**Comment by gsouf** [comment]
@1st1 I believe I was using noce 10.x

**Comment by haikyuu** [comment]
I'm using latest node 12.

**Comment by jaclarke** [comment]
I believe this issue is fixed in the latest versions. The `createClient()` API (`connect()` is deprecated now) accepts a `waitUntilAvailable` option (defaults to 30s), and will retry attempts to connect for that time before failing.
