### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT while connecting to edgedb instance via DSN

### ISSUE THREAD

**Issue by vivek9patel** [edgedb/edgedb-js#433]
**Describe the bug**
I have an edgedb instance running on the Kubernetes cluster on google cloud (I followed the steps from docs to deploy the instance on GCP). I'm getting DEPTH_ZERO_SELF_SIGNED_CERT error while connecting to it. I'm attaching the TLS certificate file which I copied from cluster's info.

**Reproduction**
 I've the DSN for that instance, and I'm passing it to connect like this:

```typescript
const client = edgedb.createClient({dsn: process.env.EDGEDB_DSN}) 
```

**Expected behavior**
But when do a request instead of connecting and running the query, It gives me this error (you can see the EDGEDB_DSN in the first line):
<img width="486" alt="Screen Shot 2022-08-24 at 6 24 41 PM" src="https://user-images.githubusercontent.com/50517245/186553498-21847d9a-9c64-456f-a5d7-f3e1a4f2def7.png">

**Versions
 - OS: macOS 12.5
 - EdgeDB version: e.g. `2.0`
 - `edgedb-js` version: e.g. `0.20.10`

**Comment by colinhacks** [comment]
We deprecated `tls_cert_file` in favor of `tls_ca_file`. Looks like the docs were our of date, sorry about that :( Give that a shot and report back.

**Comment by vivek9patel** [comment]
Thanks, got resolved with that!
