### ISSUE TITLE
Incorrect return type (or type inference) on bulk insert+select

### ISSUE THREAD

**Issue by jackfischer** [edgedb/edgedb-js#459]
[Follow up from discord](https://discord.com/channels/841451783728529451/849374705210490900/1029137172198064268) 

**Code**

```typescript
const diffInsertQueries = diffs.map(diff =>
  e.insert(e.StrategyNodeEdit, {
    fromType: diff.from_type,
    toType: diff.to_type,
    oldNode: diff.oldNode,
    newNode: diff.newNode,
  })
);

const query = e.select(
  e.set(...diffInsertQueries),
  (sne) => e.StrategyNodeEdit["*"],
);

const insertedEdits = await query.run(tx);
```

This type checks to the following, note the `[]`
```typescript
const insertedEdits: {
    id: string;
    fromType: string | null;
    newNode: unknown;
    oldNode: unknown;
    toType: string | null;
}[]
```

**Schema**

```
    type StrategyNodeEdit extending SignalSubject {
            property fromType -> str;
            property toType -> str;
            property oldNode -> json;
            property newNode -> json;
    }
```

**Generated EdgeQL**

EdgeQL for single insert/select (`diffs`/ `diffInsertQueries` is an array of one element)

```
WITH
  __scope_0_defaultStrategyNodeEdit := (
    { (INSERT default::StrategyNodeEdit {
      toType := "Objective",
      newNode := to_json($${"title":"example new node","nodeType":"Objective","tiptapId":"2449440c-0d08-4452-9d64-ca27c6786bbc"}$$)
    }) }
  )
SELECT __scope_0_defaultStrategyNodeEdit {
  fromType,
  newNode,
  oldNode,
  toType,
  id
}
```

EdgeQL for multiple insert/selects (`diffs`/ `diffInsertQueries` is an array of size >1)

```
WITH
  __scope_0_defaultStrategyNodeEditUNIONdefaultStrategyNodeEdit := (
    { (INSERT default::StrategyNodeEdit {
      toType := "Objective",
      newNode := to_json($${"title":"example new node","nodeType":"Objective","tiptapId":"e7ce52f4-f62c-493d-85c7-b6ce86fedf7c"}$$)
    }), (INSERT default::StrategyNodeEdit {
      toTitle := "example second node",
      toType := "Objective",
      newNode := to_json($${"title":"example second node","nodeType":"Objective","tiptapId":"a2017710-63e7-4a06-ab17-a7a45ff804e1"}$$)
    }) }
  )
SELECT __scope_0_defaultStrategyNodeEditUNIONdefaultStrategyNodeEdit {
  fromType,
  newNode,
  oldNode,
  toType,
  id
}
```

**Error or desired behavior**

Expected behavior: `insertedEdits` would always be an array, including an array of size 1 when there is only one object returned, corresponding to the type inference. 
Actual behavior: if only one object is inserted+selected, `insertedEdits` is of the type below at runtime, not wrapped in an array
```
{
    id: string;
    fromType: string | null;
    newNode: unknown;
    oldNode: unknown;
    toType: string | null;
}
```

`insertedEdits` _could_ also be a union type of the array and non-array version but this is obviously more of a headache for development.

**Versions (please complete the following information):**
 - OS: macOS 12.6 (21G115)
 - EdgeDB version 2.3+5b90060
 - `edgedb-js` version 0.22.8

**Comment by jackfischer** [comment]
Further context that's perhaps a separate issue but want to mention: have further noticed that these queries are _cripplingly_ slow, comes out to about ~100ms for each query in `diffInsertQueries`.

**Comment by 1st1** [comment]
@jaclarke can you take a look at this?

**Comment by jackfischer** [comment]
Fixed in 1.x!
