### ISSUE TITLE
Filter_single on select query returns a singleton but typescript expects an array

### ISSUE THREAD

**Issue by franckdsf** [edgedb/edgedb-js#471]
**Code**

This query is supposed to return a single user (and does), but typescript expects an array to be returned.

```typescript
    const user = await e.select(e.User, () => ({ filter_single: { id: '<some-id>' } })).run(client);
    // edgedb returns a singleton {id: string} but typescript expects it to be {id: string}[] 
```

**Error**

![Capture d’écran 2022-10-27 171650](https://user-images.githubusercontent.com/55093431/198344972-2c36a927-ccb7-43fa-b654-29bca99a4154.png)

**Solution**

Make filter_single queries return a singleton type, not an array.

**Workaround**

For now the workaround is to cast the result.
```typescript
    const userObject = user as unknown as typeof user[number];
    // type : {id: string} and not {id: string}[] anymore
```

**Versions:**
 - OS: Windows 11
 - EdgeDB version : 2.5
 - `edgedb-js` version : 1.0.0

**Comment by jaclarke** [comment]
I can't reproduce this bug: 
![image](https://user-images.githubusercontent.com/2085287/199309015-39ecb467-00a1-4415-9516-94e17c2b4041.png)

Which typescript version and generation options are you using?

**Comment by franckdsf** [comment]
Hey @jaclarke  my typescript version is 4.7.4 and my tsconfig looks like this :

```ts
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "outDir": "./dist",
    "baseUrl": "./src",
// ...............
```

It was because of ```   "strictNullChecks": false,```, I switched it to true and I now have the same result as yours.
