### ISSUE TITLE
`generate queries` fails with SchemaDefinitionError - migration parent is not the most recent migration

### ISSUE THREAD

**Issue by MiroslavPetrik** [edgedb/edgedb-js#476]
**Describe the bug**
I have one `.edgeql` file with simple query & I want to generate typescript queries with `npx @edgedb/generate queries --target ts`.
This fails with `SchemaDefinitionError` saying the migration is not the most recent migration, while `edgedb migration status` returns the same hash, which is mentioned in the error:

![unknown](https://user-images.githubusercontent.com/38855190/199206057-cd961765-2fd2-4345-9f9b-05479096a451.png)

**Reproduction**
`npx @edgedb/generate queries --target ts`

**Expected behavior**
The queries should be generated.

**Versions
 - OS: Windows 11
 - EdgeDB version: 2.5+57f782 (from `edgedb instance list`)
 - `edgedb-js` version: 1.0.0
 - `@edgedb/generate` version: "0.0.3"

**Additional context**
original discord thread
https://discord.com/channels/841451783728529451/849374705210490900/1034863080678629508

**Comment by eliassjogreen** [comment]
I also get the same error when trying it from `wsl` and powershell, with and with all codegen target platforms.

**Comment by jaclarke** [comment]
It seems the generator isn't properly filtering out the `.edgeql` files in the `dbschema/migrations` directory on Windows. I'll publish a bugfix release shortly with a fix for this issue (https://github.com/edgedb/edgedb-js/pull/475/commits/6ff50b2c0c01c8f5ba6f14be4f29eccd466e32b2).
