### ISSUE TITLE
Fetch api lacks a method to fetch an optional single object

### ISSUE THREAD

**Issue by RobertoPrevato** [edgedb/edgedb-js#48]
The `AwaitConnection` from "edgedb/dist/src/client" exposes the following methods to fetch items:

* fetchOne
* fetchOneJSON
* fetchAll
* fetchAllJSON

![image](https://user-images.githubusercontent.com/2576032/82495370-4abb4380-9aeb-11ea-9b25-60c16b4573c0.png)

The `fetchOne` method throws exception if a filter produces no results:

```Error: query returned no data```

Because internally it is configured with a flag `expectOne` set to true:

![image](https://user-images.githubusercontent.com/2576032/82496383-eef1ba00-9aec-11ea-925e-2ce1556cebf4.png)

However, it often happens to desire to fetch an optional object. In simple words: "fetch the first item of the query, or nothing if none is found".

For example, in .NET System.Linq implements these two methods:

```
collection.First(item => item.Id == "example");    
// this throws exception if the call produces no result, because the collection 
// is expected to have at least one matching item

collection.FirstOrDefault<T>(item => item.Id == "example");   
// this returns the first matching item, or default(T), which in most circumstances 
// is `null`
```

As a side note, it also exposes methods that cause exception if the collection contains more than one matching item by predicate:

* .Single(Func<TSource,Boolean> predicate) -> TSource
* .SingleOrDefault(Func<TSource,Boolean> predicate) -> TSource or default(TSource)

---
A consequence of the missing API, considering that exceptions are expensive in JavaScript, is that for optional items we need to fetch a list of items, and then read the first element of the list.

For example:

```ts
    const items = await connection.fetchAll(
      `SELECT Foo {
        name
        creation_time
      }  FILTER .id = <uuid>$id;`,
      {
        id: fooId
      }
    )

    if (!items.length)
      // foo not found
      return null;
  
  return items[0];
```

Proposal:
* enable overriding the parameter `expectOne` in the `fetchOne` signature,
* or, include a function like: `fetchOneOrNull`,
* or, a function like: `fetchOneOrDefault`, e.g:

```ts
  async fetchOneOrDefault(
    query: string, 
    args: QueryArgs = null, 
    default: any = null
  ): Promise<any> {
    this._enterOp();
    try {
       const items = await this._fetch(query, args, false, false);
       return items.length ? items[0] : default;
    } finally {
      this._leaveOp();
    }
  }
```

**Comment by 1st1** [comment]
Got it. I think adding a `default` parameter to both python/js APIs makes sense.

**Comment by 1st1** [comment]
Actually adding the `default` parameter to Python API would be problematic as it currently expects `(*args, **kwargs)`

Maybe `fetchOneOrNull` / `fetchOneOrDefault` makes more sense and would work for both Python & JS bindings.

Another idea would be to use something like:

```
await con.withDefault(42).withTimeout(10).fetchOne(...)   // js
await con with_timeout(10).fetchone(...)   # python
```

@elprans any thoughts?

**Comment by elprans** [comment]
I think `fetchOneOrDefault` is the best approach.  It's explicit and readable.  Also, timeouts should probably be handled externally, i.e. `wait_for` in Python (and something like [await-timeout](https://www.npmjs.com/package/await-timeout) in JS).

**Comment by 1st1** [comment]
> Also, timeouts should probably be handled externally, i.e. wait_for in Python 

`wait_for` is slow.

> and something like await-timeout in JS

:) And what do you think await-timeout does? There's no promise cancellation API in JS, so if we want to have cancellation / timeouts that actually work we'll need our own APIs for that.

**Comment by elprans** [comment]
> And what do you think await-timeout does?

As far as I can see you're supposed to do `Promise.race()` with it, which would `reject()` the query promise.

**Comment by 1st1** [comment]
> As far as I can see you're supposed to do Promise.race() with it, which would reject() the query promise.

You're reading the documentation wrong. There's no way for the code that is wrapped into a Promise to know it needs to cancel. There's no commonly adopted or standardized cancellation API in JS, period. https://stackoverflow.com/questions/30233302/promise-is-it-possible-to-force-cancel-a-promise

**Comment by 1st1** [comment]
And this is why we'll need to come up with our own cancellation API for JS anyways, and I'm thinking what I suggested in https://github.com/edgedb/edgedb-js/issues/48#issuecomment-632243674 kind of makes sense (the JS part, specifically).

**Comment by jaclarke** [comment]
Implemented in https://github.com/edgedb/edgedb-js/commit/636697e67bf5c82a2ead800daa02392697e3d88f
