### ISSUE TITLE
`deno compile` results in "Module not found"

### ISSUE THREAD

**Issue by NetOpWibby** [edgedb/edgedb-js#495]
**Error or desired behavior**

```
deno compile --allow-env --allow-net --allow-read --unstable main.ts
> Check file:///~/pastry-server/main.ts
> Compile file:///~/pastry-server/main.ts
> Emit pastry-server

./pastry-server
error: Module not found
```

**My app works perfectly fine not compiled.**

Initially, I thought my issue with compilation might have to do with an npm module I was using but I refactored it into my project and the issue persists. The only other dependencies I have come from Deno's std library.

**Versions (please complete the following information):**
 - OS: macOS Ventura
 - EdgeDB CLI 2.0.5+53f9c9b
 - `edgedb-js` version 1.0.1

**Comment by jaclarke** [comment]
As far as I can tell this error is related to using an import map, and this bug in `deno compile`: https://github.com/denoland/deno/issues/14246. It seems that if you have a `deno.json` config file that specifies an import map, then the compiled binary ends up ignoring it, so you get the 'module not found' errors. The workaround for now appears to be to explicitly pass the `--import-map` option to `deno compile`, which in my testing does seem to create a working binary.

**Comment by NetOpWibby** [comment]
I guess that's it! Sweet.

I wish Deno included non-JS/TS files (like `edgedb.toml`) but that's a problem for another day. Thanks @jaclarke!
