### ISSUE TITLE
Add a connection pool

### ISSUE THREAD

**Issue by 1st1** [edgedb/edgedb-js#5]

**Comment by haikyuu** [comment]
Is there some progress on this? 

In the meantime, what should i do to circumvent this limitation? Should i open a new connection for each request? Or is there another way?

I did some research and it seems like there is a generic pool https://www.npmjs.com/package/generic-pool.

I'll give it a try and share my findings

**Comment by haikyuu** [comment]
I tried using the generic pool and it didn't work reliably.

Is there a way to access:
- The number of open connections
- Memory used by edgedb

Those will help me debug.

For now, when i run `edgedb service`, i notice these processes are run

![image](https://user-images.githubusercontent.com/8558836/75616582-f3907d00-5b52-11ea-98e7-2ea634af9576.png)

**Comment by 1st1** [comment]
> In the meantime, what should i do to circumvent this limitation? Should i open a new connection for each request?

Yeah, without a proper pool that's the only solution. Or use edgeql+http or graphql+http port (that way you essentially have a server-side connection pooling).

> The number of open connections

Not yet. We need to add that.

**Comment by haikyuu** [comment]
@1st1 
> server-side connection pooling
What do you mean? Is it the maximum number of connections i specify when configuring a `Port`?

**Comment by 1st1** [comment]
The `concurrency` setting of a `Port` corresponds to two things: the number of Python compiler processes and the number of Postgres connections in the pool of this port.  Setting `concurrency := 5` means that there will be 5 postgres connections in the pool managed for you automatically.

**Comment by haikyuu** [comment]
@1st1 I'm interested in implementing a pool for the js driver. Can you help me in that? from where should i start? How is it done in EdgeDB side of things? ... 

I know you've implemented one for the python driver so you have more context about that. 
Thank you

**Comment by 1st1** [comment]
> I know you've implemented one for the python driver so you have more context about that.

I'd start with examining the Python implementation and prototyping a JS one based on it. Maybe we can start drafting the API / types / methods / functions first (using the TS syntax).

**Comment by haikyuu** [comment]
Sure, let's do that.

This is a direct port the python driver pool:

![image](https://user-images.githubusercontent.com/8558836/76691657-59016500-664d-11ea-865d-27068f39f061.png)

```typescript
import {ConnectConfig} from "./con_utils";
import {Connection} from "./client";

interface PoolConfig{
    connectionConfig: ConnectConfig,
    minSize: number,
    maxSize: number,
    onRelease?: ReleaseCallback,
    onAcquire?: AcquireCallback,
    onConnect?: ConnectCallback,
}

interface createPool {
  PoolConfig: Promise<Pool>
}
interface ReleaseCallback{ void: any }
interface AcquireCallback{ void: any }
interface ConnectCallback{ Connection: any }

interface Pool{
  acquire (): Promise<Connection>
  release (Connection): Promise<void>
  terminate (): Promise<void>
  close (): Promise<void>
  expireConnections (): Promise<void>
  setConnectionArguments (ConnectConfig): Promise<void>
}
```
What's the use of the Proxy that is passed to the acquire callback in the python driver?

**Comment by haikyuu** [comment]
@1st1 what do you think about these definitions? Should we move forward?

I think the first thing we should implement is the `acquire` method.

I sketched a little drawing that shows how `acquire` works under the hood. I'd like to get your feedback on it.
![acquire](https://user-images.githubusercontent.com/8558836/76845608-6da54f00-683f-11ea-8213-f59f90fff9da.png)

**Comment by 1st1** [comment]
Huge thanks, @haikyuu, this is great start. A few thoughts:

* `onRelease`, `onAcquire`, and `onConnect` should accept promise-returning functions, so that it's possible to use async functions for them. 

  So `interface ReleaseCallback{ void: any }` becomes `type ReleaseCallback = (connection: Connection) => Promise<void>`.

* We need to implement proxy objects for Connections. The idea is that our Pool would not give you a real `Connection` object, but instead return a wrapper. A wrapper is only valid to use until it's released.

  This makes it difficult for people to accidentally re-use already released connections.

  Essentially it means that `Pool.acquire` would be defined as `acquire() => Promise<ConnectionProxy>`. All other connection-returning or -accepting APIs should work with proxies.

* `expireConnections` and `setConnectionArguments` are rather low priority, we don't need them in the very first iteration.

* Regarding implementation: we want to keep edgedb-js to have 0 dependencies. Means that we'll probably need to implement a LIFO queue ourselves; good news is that 70% of it are already implemented in `lru.ts`.

Other than that the diagram looks correct!
