### ISSUE TITLE
Possible buffer allocation bug?

### ISSUE THREAD

**Issue by qm3ster** [edgedb/edgedb-js#50]
Shouldn't `__realloc` also set `this.size = newSize`?
https://github.com/edgedb/edgedb-js/blob/99f558ccd377706435a599af106099b3b00890e6/src/buffer.ts#L59-L71
Otherwise subsequent reuse would reallocate and copy all over again, even though there's actually enough buffer, it's just not reflected in `this.size`?

**Comment by 1st1** [comment]
Ah, good catch. The only reason we didn't really notice this is because our writes are smaller than 4kb.
