### ISSUE TITLE
Query builder offline generator

### ISSUE THREAD

**Issue by kyuuaria** [edgedb/edgedb-js#511]
**Describe the proposed feature**
Add something like a `--offline` option to the query builder generator that allows generating the query builder from just the schema without connecting to the database. This would be super useful for CI/CD purposes since you wouldn't have to include the generated files into version control.

**Comment by Mathias-Boulay** [comment]
Pretty sure the documentation mentions this won't be done
![image](https://user-images.githubusercontent.com/24864674/208497810-1ce1fdb2-aef1-41b6-b2ec-2729233ddc98.png)

Regarding your CI/CD issue though, maybe make it instantiate a DB to generate the files on the fly if that needed :thinking:

**Comment by kyuuaria** [comment]
Sorry I must have overlooked that
