### ISSUE TITLE
npx @edgedb/generate interfaces --out option not working

### ISSUE THREAD

**Issue by NexZhu** [edgedb/edgedb-js#515]
**Describe the bug**
`npx @edgedb/generate interfaces --out`
`--out` option is not working
`interfaces.ts` still generated into `dbschema/interface.ts`

**Comment by NexZhu** [comment]
Also not working for `edgeql-js`

**Comment by jaclarke** [comment]
The `--out` (or `--output-dir`) option is not valid for the `interfaces` or `queries` generators, instead you should use the `--file` option. Currently it seems the `--help` output is outdated and doesn't mention the `--file` option, but this PR should fix this: https://github.com/edgedb/edgedb-js/pull/521

**Comment by jaclarke** [comment]
> Also not working for edgeql-js

I can't reproduce this. Can you give more details, like the `@edgedb/generate` version, the command you're running and the output (is there an error or does it generate into the wrong directory)?

**Comment by NexZhu** [comment]
With `"@edgedb/generate": "^0.0.7"` `dotenv npx @edgedb/generate interfaces --file src/models/generated/interface.ts` still generates to `./dbschema/interfaces.ts`
```
> deepkit-starter@0.0.1 edgedb:gen:interfaces /root/dev/web/daotl-deepkit-starter
> dotenv npx @edgedb/generate interfaces --file=src/models/generated/interface.ts

Generating TS interfaces from schema...
Introspecting database schema...
Generating interfaces...
Writing interfaces file...
   ./dbschema/interfaces.ts
Generation complete! 🤘
```

**Comment by jaclarke** [comment]
The issue there seems to be with the usage of `dotenv` (I'm assuming this is https://www.npmjs.com/package/dotenv-cli). The `--help` output of `dotenv` states: `` `command` is the actual command you want to run. Best practice is to precede this command with ` -- `. Everything after `--` is considered to be your command. So any flags will not be parsed by this tool but be passed to your command. If you do not do it, this tool will strip those flags``.

So the `--file` option is being stripped by `dotenv` and `@edgedb/generate` never sees it. The fix appears to be to run it like this:
```
dotenv -- npx @edgedb/generate interfaces --file=src/models/generated/interface.ts
```

**Comment by NexZhu** [comment]
Thanks! My bad.
