### ISSUE TITLE
Add source and source maps to npm packages

### ISSUE THREAD

**Issue by vjjft** [edgedb/edgedb-js#560]
For the npm packages, since the modules are written in TS, it would be very helpful if the source and source maps were included in the package.

Currently, if one wants to inspect the implementation to understand what the API or utility is doing, it is very difficult.

**Comment by scotttrinh** [comment]
Thanks for the suggestion! I don't think we're likely to increase the package size for everyone to make it easier to inspect the implementation, but I'll consider what utility generating and including source maps might have versus the increased package size. I believe some IDEs can download the source and link the source map even if we do not provide it, but I'll have to do a little investigation.

No firm plans to make any changes here for now, so I'm going to close this, but please feel free to add any additional thoughts or context here.
