### ISSUE TITLE
Consider removing 'node-fetch' import for http client

### ISSUE THREAD

**Issue by jaclarke** [edgedb/edgedb-js#566]
Currently the http client `requires` the `node-fetch` library if `fetch` doesn't exist. However this seems to cause build errors in nextjs if 'node-fetch' isn't a dependency, even though the framework already polyfills the `fetch` api.
So since either most runtimes now natively support `fetch` (eg. node 18, deno, vercel edge runtime, cloudflare workers) or the framework polyfills it (eg. nextjs, remix), I think it's ok to drop the 'node-fetch' import, and just assume that the fetch api exists (or if not, require users to install a polyfill themselves).

**Comment by devunt** [comment]
Requiring `node-fetch` also makes the build failing in Vercel edge functions (which doesn't have node)

**Comment by mcgrealife** [comment]
Confirmed in nextjs edge runtime. Here are the error logs from next build. 

```
Failed to compile.

./node_modules/edgedb/dist/httpScram.js:18:0
Module not found: Can't resolve 'node-fetch'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/edgedb/dist/fetchConn.js
./node_modules/edgedb/dist/browserClient.js
./node_modules/edgedb/dist/index.browser.js
./src/pages/api/edgeRuntime.ts
~
```

(thanks for articulating this @jaclarke!)

**Comment by maks112v** [comment]
Is there a fix for this? I am running into the issue also on a new nextjs app

**Comment by mcgrealife** [comment]
@maks112v one temporary dirty workaround is to:
- in `node_modules`, find the `node_modules/edgedb/dist/httpScram.js` file
- around line 18, change `const FETCH = typeof fetch === "undefined" ? require("node-fetch") : fetch` to simply `const FETCH = fetch`
- delete the `.next` folder (generated by next build)
- re-build the next app `npm run build` or `yarn build`

![edit-node-module-file](https://user-images.githubusercontent.com/11381911/230476675-6d31a3e0-33e8-474e-bcb2-43daa4b003e9.png)

**Comment by scotttrinh** [comment]
@maks112v 

I've fixed this in my Next.js v13 app by actually installing `node-fetch` (v2 for CJS compatibility) and then setting it as an server component external package in my `next.config.js`:

```js
const nextConfig = {
  // ... your config
  experimental: {
    // ... your experimental config
    serverComponentsExternalPackages: ["node-fetch"],
  },
};

module.exports = nextConfig;
```

**Comment by zetashift** [comment]
In a Nx monorepo I had a problem with `fetch` as well:

```
$ npx projen build
       👾 build » post-compile » synth:silent | cdk synth -q
       Bundling asset mic-platform-dev/micapi/Code/Stage...
       $ /home/rishi/dev/work/micx/node_modules/.bin/esbuild --bundle /home/rishi/dev/work/micx/packages/mic-platform/src/router.ts --target=node18 --platform=node --outfile=/home/rishi/dev/w
ork/micx/packages/mic-platform/cdk.out/bundling-temp-16b921ba0df10cf88094ec366b0fddd9211a2c85fc62f328ea00042504b1cb95/index.js '--external:@aws-sdk/*'
       ✘ [ERROR] Could not resolve "node-fetch"

           node_modules/edgedb/dist/httpScram.js:18:57:
             18 │ ...CH = typeof fetch === "undefined" ? require("node-fetch") : fetch;
                ╵                                                ~~~~~~~~~~~~

         You can mark the path "node-fetch" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.

       1 error
       node:child_process:924
           throw err;
           ^
```

Even though I'm using Node.js it seems to still see `fetch` as undefined. Might be related: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/60924
