### ISSUE TITLE
Edge runtime compatibility (Vercel, Cloudflare workers...)

### ISSUE THREAD

**Issue by dotlouis** [edgedb/edgedb-js#570]
Hi all,

I tried using the HTTP client to make EdgeDB work onto Vercel's [edge runtime](https://beta.nextjs.org/docs/rendering/edge-and-nodejs-runtimes) as there are non-negligible gains (on cold boots). But with no success.

It seems the query-builder uses node's crypto module.
Is there any plan on supporting the edge runtime sometime in the future ?

Bests

**Comment by PastelStoic** [comment]
To clairify: does this issue exist for only the query builder, or does it also affect raw queries/query generator?

**Comment by scotttrinh** [comment]
We use `node:crypto` in the database driver itself, so it affects both the generator and raw queries.
