### ISSUE TITLE
EdgeQLSyntaxError: Unexpected keyword "IN" / mixing string type literals and type names is not supported

### ISSUE THREAD

**Issue by NetOpWibby** [edgedb/edgedb-js#577]
**Code**
The code causing the error.

```typescript
(async() => {
  let databaseQuery;

  switch((query.type as Record["type"])) {
    case "A":
    case "AAAA":
    case "CNAME":
    case "DNAME":
    case "NS":
    case "PTR": {
      databaseQuery = e.select(
        e.insert(e.PlainRecord, { ...query }),
        () => ({ ...e.PlainRecord["*"] })
      );
      break;
    }

    default: {
      break;
    }
  }

  try {
    response = await databaseQuery.run(client);
    return { detail: response };
  } catch(_) {
    return { detail: response };
  }
});
```

**Schema**

Your application schema.

```
module default {
  scalar type ClassType extending enum<"CH", "CS", "HS", "IN">;

  abstract type BaseRecord {
    required property class -> ClassType;
    required property created -> datetime {
      default := datetime_of_transaction();
      readonly := true;
    };
    required property name -> str;
    required property ttl -> float64;
    required property type -> RecordType;
    required property updated -> datetime {
      default := datetime_of_transaction();
    };
  }

  type PlainRecord extending BaseRecord {
    required property data -> str;
  }
}
```

**Generated EdgeQL**

```
SELECT (INSERT default::PlainRecord {
  name := "app.beachfront",
  type := default::RecordType.A,
  class := default::ClassType.IN,
  ttl := 300
}) {
  data,
  class,
  name,
  ttl,
  type,
  created,
  updated,
  id
}
```

**Error or desired behavior**

<img width="972" alt="SS 2023-04-20 at 1 23 12 PM" src="https://user-images.githubusercontent.com/1288356/233479738-3114a561-8839-460a-9772-3d01a25fd3db.png">

**Versions (please complete the following information):**

- OS: macOS Ventura
- EdgeDB version (e.g. `2.0`): 2.5+5f12a50
- EdgeDB CLI version (e.g. `2.0`): 2.3.1+5d93f42
- `edgedb-js` version (e.g. `0.20.10`;): 1.1.0 (latest Deno version)
- `@edgedb/generate` version (e.g. `0.0.7`;): 1.1.0 (latest Deno version)
- Typescript version: 5.0.3
- Deno version: 1.32.2 (release, aarch64-apple-darwin)

**Comment by NetOpWibby** [comment]
The `mixing string type literals and type names is not supported` error was achieved by replacing quotes with backticks around `IN` in my schema.

**Comment by NetOpWibby** [comment]
> Meaning that you updated it to include the backtick version

Correct. I then tried to do something like 

```
scalar type ClassType extending enum<"CH", "CS", "HS", "`IN`">;
```

but got

> edgedb error: InvalidValueError: invalid input value for enum 'default::ClassType': "IN"

I'll try the backtick transform in my code.

**Comment by NetOpWibby** [comment]
@scotttrinh EdgeDB returned with this:

```
Error: Invalid value for type default::ClassType: "`IN`"
    at literalToEdgeQL (file:///~/dbschema/edgeql-js/toEdgeQL.ts:1430:15)
    at renderEdgeQL (file:///~/dbschema/edgeql-js/toEdgeQL.ts:857:12)
    at shapeToEdgeQL (file:///~/dbschema/edgeql-js/toEdgeQL.ts:1334:26)
    at renderEdgeQL (file:///~/dbschema/edgeql-js/toEdgeQL.ts:1026:10)
    at renderEdgeQL (file:///~/dbschema/edgeql-js/toEdgeQL.ts:910:31)
    at Proxy.$toEdgeQL (file:///~/dbschema/edgeql-js/toEdgeQL.ts:296:16)
    at Proxy.$queryFunc (file:///~/dbschema/edgeql-js/query.ts:28:22)
    at Object.default [as createRecord] (file:///~/src/api/component/record/crud/create.ts:148:36)
    at eventLoopTick (ext:core/01_core.js:166:11)
    at async runHttpQuery (https://deno.land/x/alpha@2023.04.10/src/common.ts:40:10)
```

Data supplied to EdgeDB:

```js
{ name: "app.beachfront", type: "A", class: "`IN`", ttl: 300 }
```

**Comment by jaclarke** [comment]
@scotttrinh I think this is a bug in querybuilder. In the edgeql codegen it looks like we're not correctly quoting enum values that are also keywords, ie. the generated edgeql should be:
```edgeql
SELECT (INSERT default::PlainRecord {
  name := "app.beachfront",
  type := default::RecordType.A,
  class := default::ClassType.`IN`,
  ttl := 300
}) {
  data,
  class,
  name,
  ttl,
  type,
  created,
  updated,
  id
}
```

**Comment by scotttrinh** [comment]
@jaclarke 

Quoting should be done at query time or at schema defintion time or both?

**Comment by NetOpWibby** [comment]
Is the Deno library gonna get updated? It's still on 1.1.0 and there was a new repo release last week.

**Comment by NetOpWibby** [comment]
I finally had a chance to test the Deno release. Recompiled the query builder and am now getting a different error:

```
reservedKeywords.includes is not a function
```

I don't _think_ this error is coming from my project as I don't have anything called `reservedKeywords` in my codebase.

**Comment by scotttrinh** [comment]
We recently switched from an array to a set for quoting these keywords. You'll need to regenerate your query builder code from the latest verison which should properly generate a call to `has` instead of `includes`.

**Comment by NetOpWibby** [comment]
Guess I gotta wait for v1.2.3 for Deno to release. Idk how to use Github releases.

**Comment by scotttrinh** [comment]
@NetOpWibby 

No, this should be working with the latest release on deno.land as well, just make sure you regenerate your edgeql-js files after updating.

**Comment by NetOpWibby** [comment]
It doesn't.

I was already using the latest. Noticed something interesting though...when I omit the version like so:

```
deno run -A --unstable https://deno.land/x/edgedb/generate.ts edgeql-js --instance nameserver --database nameserver
```

I get

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'setNextTickCallback')
core.setNextTickCallback(processTicksAndRejections);
     ^
    at https://deno.land/std@0.115.0/node/_next_tick.ts:206:6
```

The below command doesn't have that issue:

```
deno run -A --unstable https://deno.land/x/edgedb@v1.2.2/generate.ts edgeql-js --instance nameserver --database nameserver
```

**Comment by scotttrinh** [comment]
Hmmm... Looks like there is some part of the bits that copy files at build time to the `edgedb-deno` repo that just isn't getting updated with the current publishing setup. Will look into this.

**Comment by NetOpWibby** [comment]
1.3.0 works!

**Comment by scotttrinh** [comment]
Ah, thanks for verifying @NetOpWibby ! I meant to leave a note here that the latest release fixed the stale file bug with the Deno release, so glad it worked.
