### ISSUE TITLE
Web REPL errors when subtracting a duration from a date results in a date before 2001-01-01

### ISSUE THREAD

**Issue by raddevon** [edgedb/edgedb-js#652]
```
select datetime_current() - <cal::relative_duration>'23 years 164 days 21 hours 53 minutes';
```

This query currently fails in the web REPL with `RangeError: invalid number of microseconds -271: expected a value in 0-999 range`, but it will likely succeed by the time you are working this issue. Swap in a larger duration to see the failure.

```
select datetime_current() - <cal::relative_duration>'40 years';
```

**Comment by jaclarke** [comment]
In the ui we force `datetime`s to be decoded as `cal::local_datetime` so we don't lose microsecond precision (https://github.com/edgedb/edgedb-js/pull/353). It looks like that custom codec isn't handling 'negative' dates correctly.
