### ISSUE TITLE
double-splat syntax doesn't work

### ISSUE THREAD

**Issue by CSFlorin** [edgedb/edgedb-js#659]
**Describe the bug**
v3 introduces double-splat syntax for getting all properties and links
<img width="690" alt="image" src="https://github.com/edgedb/edgedb-js/assets/9855031/d2c4651c-15bd-4210-a5d3-598b080ac2e4">
<img width="843" alt="image" src="https://github.com/edgedb/edgedb-js/assets/9855031/36fd07c2-f3e3-4cf4-a48e-e0323cb11dc6">
https://github.com/edgedb/rfcs/blob/master/text/1023-splats.rst

but it doesn't work in the TypeScript client.

**Reproduction**

```typescript
t['**']
```

**Expected behavior**
It gets all properties and links from the selected type

**Versions (please complete the following information):**

- OS:
- EdgeDB version (e.g. `2.0`): 3.0-rc.5
- EdgeDB CLI version (e.g. `2.0`): 0.2.1
- `edgedb-js` version (e.g. `0.20.10`;): 0.2.1
- Node/Deno version: 16.13.0

**Additional context**

**Comment by scotttrinh** [comment]
Yep! Already tracking in #558, feel free to subscribe over there. No specific timeframe for this, but it's on my shortlist!

**Comment by CSFlorin** [comment]
Thanks sorry about that, I searched issues for "**" and didn't find anything
