### ISSUE TITLE
(Generate queries) Add ignore require-await rule for deno exports

### ISSUE THREAD

**Issue by PastelStoic** [edgedb/edgedb-js#672]
Due to the output structure, the default deno linter complains about the generated queries not using await. Adding 
`// deno-lint-ignore-file require-await`
to each generated file would prevent this error.

**Comment by scotttrinh** [comment]
Thanks for the report! PRs welcome, but I put it in my backlog if no one else gets to it in the next few weeks.

**Comment by davepar** [comment]
Just a friendly ping that this is still an issue. The merged PR is adding a `deno-lint-ignore-file` for the file, but it's after an `import type` statement. This causes deno to ignore it. The line doesn't have to be at the top, but does need to be before any statements. See the [deno docs](https://docs.deno.com/runtime/manual/tools/linter#files) for details.

I can try this minor fix if nobody else is looking at it.

**Comment by PastelStoic** [comment]
Now that I look more closely - is the `async` keyword actually needed? A promise is returned with or without it.

**Comment by scotttrinh** [comment]
Fixed in #812
