### ISSUE TITLE
TypeScript transpilation throws "Type 'E[j][k]' does not satisfy the constraint"

### ISSUE THREAD

**Issue by sergiocarneiro** [edgedb/edgedb-js#688]
I'm using `tsc` to transpile a project that contains the dbschema.

The command is throwing the following error:

```
dbschema/edgeql-js/select.ts:114:30 - error TS2344: Type 'E[j][k]' does not satisfy the constraint 'TypeSet<BaseType, Cardinality>'.
  Type 'E[j][keyof E[j]]' is not assignable to type 'TypeSet<BaseType, Cardinality>'.
    Type 'E[j][string] | E[j][number] | E[j][symbol]' is not assignable to type 'TypeSet<BaseType, Cardinality>'.
      Type 'E[j][string]' is not assignable to type 'TypeSet<BaseType, Cardinality>'.
        Type 'E[keyof E][string]' is not assignable to type 'TypeSet<BaseType, Cardinality>'.
          Type 'E[string][string] | E[number][string] | E[symbol][string]' is not assignable to type 'TypeSet<BaseType, Cardinality>'.
            Type 'E[string][string]' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

114             : orLiteralValue<E[j][k]>;
                                 ~~~~~~~


Found 1 error in dbschema/edgeql-js/select.ts:114
```

The issue is not new, I'm experiencing it since the first version of `@edgedb/generate`.

_No further context is provided as the issue seems directly related to the internal type system, but feel free to ask._

**Comment by scotttrinh** [comment]
Based on the fact that the compiler errors appear to point to minified/obfuscated code, there is something unusual going on with your build process. No good clues here, but feel free to follow up with any details you might have.

**Comment by sergiocarneiro** [comment]
The code is straight from the edgedb generate script. In any case, the issue does not seem to appear anymore in tsc 5.0
