### ISSUE TITLE
readme of edgedb-js

### ISSUE THREAD

**Issue by fimbault** [edgedb/edgedb-js#71]
- EdgeDB Version: alpha5
- OS Version: ubuntu

Steps to Reproduce: as described in https://github.com/edgedb/edgedb-js

Here's what the readme says:
const conn = await edgedb.connect({
    user: "edgedb",
    host: "127.0.0.1",
  });

then I get the following warning:
`options` as the first argument to `edgedb.connect` is deprecated, use `edgedb.connect('instance_name_or_dsn', options)`

=> example in the npm package is not updated

not a big deal, just concerns the readme, but since it's the first thing a newcomer must do, it's worthwhile to have that uptodate

see my basic example https://github.com/fimbault/test_edgedb_js

NOTE : I've seen https://edgedb.com/blog/edgedb-1-0-alpha-5-luhman#simplified-administration-with-named-instances (to pass the instance name only) but couldn't make it to work.

**Comment by tailhook** [comment]
> NOTE : I've seen https://edgedb.com/blog/edgedb-1-0-alpha-5-luhman#simplified-administration-with-named-instances (to pass the instance name only) but couldn't make it to work.

Looks like the problem is that it tries to connect to the unix socket first:
```
Error: connect ENOENT /run/edgedb/.s.EDGEDB.10710
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```
Currently, the following works:
```javascript
const con = edgedb.connect('instance_name', {host: 'localhost'})
```
But let me fix that.

**Comment by jaclarke** [comment]
Documentation has been updated to new API's in https://github.com/edgedb/edgedb-js/commit/3079e97287cc027c944f0b6bf83e0d19298777e0 and https://github.com/edgedb/edgedb-js/pull/186/commits/4757dc798f7ff877ba7f69c11bd9b35b474764f2
