### ISSUE TITLE
Type of client.run() with filter_single incorrectly inferred as array

### ISSUE THREAD

**Issue by jvassev** [edgedb/edgedb-js#719]
**Code**
The code causing the error.

```typescript

async function test(client, id: string) {
  const myWidget = await e.select(e.default.Widget, () => ({
    filter_single: { id: id },
  })).run(client);

  // myWidget inferred as Array<{id: string}>
  if (!Array.isArray(myWidget)) {
    throw new Error("expected an array");
  }
}


```

**Schema**

Your application schema.

```
module default {
  type Widget {
    name: str;
  }
}
```

**Generated EdgeQL**

No errors in edgeql

**Error or desired behavior**

No errors at compile time. At runtime, I expect an array of objects, however I get either null of a single element. I thinks it better to fix the inferred type to be `T | null` or wrap the single result in an array.

Is there a workaround for this. Now I'm using `const myWidget: any` to

**Versions (please complete the following information):**

- OS:
- EdgeDB version (e.g. `2.0`): edgedb/edgedb:3 (docker image)
- EdgeDB CLI version (e.g. `2.0`): EdgeDB CLI 3.4.0+160d07d
- `edgedb-js` version (e.g. `0.20.10`;): 1.3.4
- `@edgedb/generate` version (e.g. `0.0.7`;): 0.3.3
- Typescript version: 5.1.3
- Node/Deno version: v16.15.0

**Comment by scotttrinh** [comment]
Yeah, I noticed that a while back, thanks for reporting. In the meantime, you can work around this by wrapping in `e.assert_single(e.assert_exists(yourQuery))`. Will fix!

**Comment by scotttrinh** [comment]
Might be related to #715

**Comment by sharifzadesina** [comment]
I don't understand this issue, right now if you use `filter_single` the result is `T | null`, what is wrong with this?

**Comment by scotttrinh** [comment]
Oh, sorry, I think I misunderstood the original report: `filter_single` will indeed give you `T | null` as @sharifzadesina pointed out, so this is working as intended.
