### ISSUE TITLE
starting index at 0 generates inconsistencies in dates

### ISSUE THREAD

**Issue by fimbault** [edgedb/edgedb-js#73]
To reproduce : 
- alpha5
- using edgedb-js

I started from https://github.com/edgedb/edgedb-js/blob/master/docs/usage.rst

And changed the date of birth to `dob: new edgedb.LocalDate(1982, 10, 28)`

The console displays
Set(1) [
  Object [ name := 'Bob, dob := LocalDate [ 1982-11-28 ] ]
]

The documentation does say that the index starts at 0, but it's still quite confusing (october or november?). Starting at 1 would probably be best to avoid mistakes.

**Comment by 1st1** [comment]
Yes, we need to implement the stable part of the https://tc39.es/proposal-temporal/docs/datetime.html spec, and that includes dates and months starting from 1.

**Comment by 1st1** [comment]
This issue should have been resolved now that we implement the Temporal spec
