### ISSUE TITLE
Initial query very slow using TS/JS client

### ISSUE THREAD

**Issue by bastien8060** [edgedb/edgedb-js#740]
**Describe the bug**
My application is rather latency critical, and it seems the first few queries always take a few seconds. That is an issue I haven't noticed on the python client. 

I guess the client could be delayed either due of lack of cache. If not that, could creating a connection to the database take this long? I would expect the database connection to be created when the client is initialized, not when the first query is ran. Especially when running `client.ensureConnected()`

**Reproduction**
Tried both, no difference:
```typescript
const client= createClient();
client.querySingle(`EDGEQL QUERY HERE`, ...params)
```
and

```typescript
const baseClient = createClient();

const configClient = baseClient.withConfig({
  "session_idle_transaction_timeout": Duration.from({ seconds: 0 }),
});

await configClient.ensureConnected();
client.querySingle(`EDGEQL QUERY HERE`, ...params)
```

**Expected behavior**
On the JS client, the first request always takes a couple seconds, regardless of how long the client has been initialized for. On the Python client, I never noticed any unsual delays. 

**Versions:**
Tried 3.x all the way to 4.0-alpha

- OS: WSL2 Ubuntu and AWS Ubuntu servers are affected
- EdgeDB version: Tried 3-x ➔ 4.0-alpha
- EdgeDB CLI version: 3.5.0+907ff37
- `edgedb-js` version: a couple versions back all the way to 1.3.6
- Node/Deno version: NodeJS v18.16.0

**Additional context**
This is currently preventing me to enter production. Here is the logs from a test-case I wrote, with a very simple query using sub-shapes.

```
Client Init took 121ms [.ensureConnected()]
Query took 287ms
Query took 5ms
Query took 4ms
Query took 4ms
```
Not using sub-shapes brings the first request down to 97ms. Removing the single cardinality in a table containing many objects, brings this up as high as 2-3sec. On a side note, it seems the `session_idle_transaction_timeout` param is not having any effects-

**Comment by scotttrinh** [comment]
Thank you for the detailed report! I have a few follow-up questions to help narrow down what might be happening here:

1. Do you notice this delay when running against a local database?
2. Is the database itself freshly launched, or is it persistent across attempts to measure this initial latency?

---

It's _possible_ that the way you're writing the query in preventing the database from being able to reuse some cache, and that you happen to be doing it slightly differently in the python client, so if you have a reduced test case you can share, that would be helpful.

For more context: If there are a lot of inlined literals in the query (as opposed to using params), the EdgeDB compiler spends a bunch of time parsing the initial query to generate the required SQL (that is then cached on subsequent queries) which _could_ explain some of this latency.

**Comment by bastien8060** [comment]
@scotttrinh Thanks for interest! I think it's a big issue for prod—

About the questions: 
- I am indeed always running the database locally
- It reproduces regardless of how long ago the database was started (Surprisingly, I've reproduced the issue after hours, days, and even weeks of uptime)
- It correlates with the creation of a client. Everytime I create a client, the first few requests of the client are slow. I also noticed this with EdgeDB UI.
- It doesn't matter if it's a simple `SELECT Base {*}` or a more complex query with sub shapes, but the delay that the query will hang for seems proportional to the complexity (both structurally and result-length wise).
- I tested with the QueryBuilder and with a queries pre written in EdgeQL and the issue reproduced the exact same way in both cases

I am almost positive this doesn't affect the Python version, but I will try reproduce it with the Python client!

Oh also, I remember profiling with clinic.js and it appeared it spent most of the time waiting for a reply from the server, but I could be wrong

**Comment by haikyuu** [comment]
I confirm, same thing happens to me

**Comment by bastien8060** [comment]
@scotttrinh Hey! I have done some more testing, and you might like this!


So lets start off with the results:
```
$ python3 test.py
Query 1
        20.45389900013106ms
        0.7790409981680568ms
        0.6727479994879104ms
Query 2
        23.451606000890024ms
        7.110459999239538ms
        6.427781998354476ms
Query 3
        23.044313998980215ms
        5.9507579971977975ms
        5.473471002915176ms
```

```
$ node test.js
Query 0
        39.94074299931526ms
        1.5861729979515076ms
        1.2127930000424385ms
Query 1
        527.1588909998536ms
        10.708825998008251ms
        9.880493998527527ms
Query 2
        309.18123700097203ms
        8.25722199678421ms
        8.137373000383377ms
```

So I created two scripts in `Python3.10.6` and `NodeJS 18.16.0`. They both do the exact same thing:
1. Load the 3 queries from files EdgeQL.query.{i}
2. For each query:
	- Create a new client
	- Run the query 3 times and calculate the time it took for the client by each call

Here is a gist: https://gist.github.com/bastien8060/3b8b28114947e0a03c5c929498449b21

**Comment by scotttrinh** [comment]
Thanks for the additional details! I'll surface to the team as well.

**Comment by scotttrinh** [comment]
@bastien8060 
Following up here:

The culprit was setting the `session_idle_transaction_timeout` configuration settings, which you were not setting in the Python code, was causing the compiler cache to be invalidated thus triggering a re-compile of the query. @jaclarke was able to reproduce the same slow-down on the Python client when configured to set the same config variable which pointed us at the server as the culprit.

We were able to pinpoint the issue and make a quick patch. This will be backported to the 3.x branch as well as being fixed on 4.x soon.

In the meantime, if that config value is not important, avoiding setting it will bring the JS client up to the same speed as the Python client. Or, if it is possible to set it at the database level, that will avoid the recompile with setting it on the session.

Note to others with similar "first query takes longer": The compiler _does_ need to compile and cache the query on the server side at least once, so the very first time a server instance sees a query it will be a little bit slower than subsequent runs. But it will not be ~400ms! If anyone else notices a huge 400x disparity between first and second runs, please feel free to open an issue on https://github.com/edgedb/edgedb.

**Comment by bastien8060** [comment]
@scotttrinh Awesome, yes this fixes it, sorry if it may look stupid but I had added it before to solve the slowness, but I can't seem to reproduce that slowness without this setting now, so I consider the issue solved. It never occured to me to try again without.

Creating a client now doesn't display such disparity, but spawning the server (regardless of the client), will bring its first request to 400ms, but however, I do consider that normal behaviour, as it doesn't sound crazy or impacting. 

One quick question, does EdgeDB UI use, or has it at some point used been affected by this bug? Just wondering if you "think" this patch will also solve EdgeDB UI's hanging issue, when refreshing the webpage?

Anyway, eitherway, great stuff and thank you!

**Comment by scotttrinh** [comment]
> One quick question, does EdgeDB UI use, or has it at some point used been affected by this bug? Just wondering if you "think" this patch will also solve EdgeDB UI's hanging issue, when refreshing the webpage?

I'm not sure, to be honest! @jaclarke do you think this particular bug might impact first load performance of the UI?
