### ISSUE TITLE
Queries never finish with Bun after 120~ seconds of idling

### ISSUE THREAD

**Issue by TechSupportJosh** [edgedb/edgedb-js#747]
**Describe the bug**
When running a program using Bun, approximately 120 seconds after an initial query is executed, attempting to run another query results in the query never finishing (and as a result, hanging the execution of the program).

**Reproduction**

```typescript
import * as edgedb from "edgedb";
import { getUser } from "./dbschema/queries";

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

const client = edgedb.createClient({ waitUntilAvailable: 0, tlsSecurity: "insecure" });

console.log("Fetching users...");
const users = await getUser(client);
console.log("Fetched users!");

for(let i = 120; i > 0; i--)
{
    console.log(`Waiting ${i} seconds`);
    await sleep(1_000);
}

console.log("Fetching users again...");
const users2 = await getUser(client);
console.log("Users fetched again!"); // This will never be reached.
```

A full standalone repo of the issue is accessible here: https://github.com/TechSupportJosh/bun-edgedb-repod
**Expected behavior**
The query does not cause the program to hang.

**Versions (please complete the following information):**
EdgeDB Version: "3.4+4fd1274"
EdgeDB CLI: "EdgeDB CLI 3.5.0+907ff37"
edgedb-js Version:
```
"@edgedb/generate": "^0.3.4",
"edgedb": "^1.3.7"
```
Bun version: 1.0.4
OS Version: WSL2 (5.10.16.3-microsoft-standard-WSL2 - Ubuntu 22.04.2 LTS)

**Additional context**
The Docker output when running the program looks something like this:
```
2023-10-12 00:37:33 bun-edgedb-test-edgedb-1  | INFO 1 2023-10-11T23:37:33.147 edb.server: Connection established to backend database: edgedb
2023-10-12 00:39:33 bun-edgedb-test-edgedb-1  | INFO 1 2023-10-11T23:39:33.167 edb.server: Connection discarded to backend database: edgedb
```
To me, it suggests that the connection gets discarded just as the query gets sent, but 🤷 

I know Bun isn't officially supported, but it'd be great to get this working. Other than this issue, I've had no issues migrating away an existing EdgeDB project to Bun.

I'm gonna spend the next few days trying to debug this myself, but I'll post here just in case any maintainer has a better guess at knowing what causes it.

**Comment by TechSupportJosh** [comment]
Just for anyone looking for a quick fix, this seems to work:

```ts
setInterval(() => {
    client.query(`SELECT 1;`);
}, 10_000);
```

**Comment by scotttrinh** [comment]
Thanks for troubleshooting! If you don't have any luck getting it working, please let us know.

**Comment by nervetattoo** [comment]
Fwiw this worked flawlessly for me in bun 1.0.5.
I upped it to 5 minutes to be sure I would catch something if it was that simple.
I'm running edgedb directly on macOs, not docker in dev, so that might be part of the piece.

Planning to replace a deno API with bun (and tbh replace everything node with bun after doing one project in bun) so I'm very curious as to what the cause might be here. Don't want to stumble into something once in production 😅 

```ts
import e, { createClient } from 'edgedb-node'

const client = createClient({
  waitUntilAvailable: 0,
  tlsSecurity: "insecure",
})

const query = e.select(e.User, o => ({
  name: true,
  limit: 1,
}))

console.log(await query.run(client))

for(let i = 300; i > 0; i -= 1)
{
    console.log(`Waiting ${i} seconds`);
    await Bun.sleep(1000)
}

console.log(await query.run(client))
process.exit(0)
```

- Edgedb:   Version: 3.3+d5734dd
- edgedb js: 1.3.3

**Comment by Jarred-Sumner** [comment]
Can you try again in the canary build of Bun? We pushed a change that feels relevant

`bun upgrade --canary`

**Comment by TechSupportJosh** [comment]
> Can you try again in the canary build of Bun? We pushed a change that feels relevant
> 
> `bun upgrade --canary`

After upgrading to canary, the query finishes as expected:

```
$ bun --version
1.0.6
```

**Comment by scotttrinh** [comment]
Thanks @TechSupportJosh for the report and @Jarred-Sumner for fixing this upstream 🙏
