### ISSUE TITLE
Add ability to provide custom deserializer to client

### ISSUE THREAD

**Issue by MrFoxPro** [edgedb/edgedb-js#749]
As far as edgeql prefer snake_case syntax, I think there should be client parameter to pass custom deserializer, so users will be able to transform retrived JSON in a way they want.
I suggest to add parameter to createClient like `deserializer` with same signature as `JSON.parse` `reviver`:

```js
JSON.parse('{ "snake_case": 5 }', function(key, value) {
  const camelCaseKey = key.replace(/([-_]\w)/g, g => g[1].toUpperCase())
  if (Array.isArray(this) || camelCaseKey === key) {
    return value
  } else {
    this[camelCaseKey] = value
  }
});
```

**Comment by scotttrinh** [comment]
While it's true that EdgeQL and the standard library have chosen snake_case as the standard, there is no reason _you_ have to prefer snake case in your schema: names are case-sensitive already.

FWIW, you can use computeds to do this explicitly, and I think for the moment we're not likely to prioritize something like this.

```ts
const results = await client.query<{ someProperty: string }[]>(`
  select Foo {
    someProperty := .some_property
  }
`);
```

or with the query builder:

```ts
const results = await e.select(e.Foo, (f) => ({
  someProperty: f.some_property,
}).run(client);
```

---

If there is some use case where you don't have control over the schema in  way that makes this especially difficult, feel free to reopen this issue and we can discuss.
