### ISSUE TITLE
Docs for bun

### ISSUE THREAD

**Issue by fredt34** [edgedb/edgedb-js#761]
Currently doc is provided for npm, pnpm, and deno was added recently.

I'm trying to use bun rather than npm, as it is much faster and simpler to use - at least for newbies like me.

Can you please consider adding doc for installing / using with bun? For instance, it would help on ˋdocs/generation.rst`.

**Comment by elprans** [comment]
Definitely!

Meanwhile, see Bun's [own guide](https://bun.sh/guides/ecosystem/edgedb).
