### ISSUE TITLE
The `resendVerificationEmail` server action in `auth-nextjs` should accept `email` param.

### ISSUE THREAD

**Issue by MiroslavPetrik** [edgedb/edgedb-js#845]
**Describe the bug**
The [emailPasswordResendVerificationEmail() server action](https://github.com/edgedb/edgedb-js/blob/fd0be5f1d31afecfe442e1083d52598c92232677/packages/auth-nextjs/src/app/index.ts#L137) should work with `email` param which is accepted on [the backend side.](https://github.com/edgedb/edgedb/blob/639c91e9207275c114828556a1b00c4a3029d8c1/edb/server/protocol/auth_ext/http.py#L624).

Currently only the `verification_token` is accepted. 

A case for the email param is, when the user is already signed in, and the verification is optional, I still want to display a button in user's profile to resend the verification email. In that case I don't have the `verification_token`, maybe the user also removed the original email where the old token was present.

**Additional context**

**Comment by scotttrinh** [comment]
Thanks for opening this issue it really is the completion of the job we did in https://github.com/edgedb/edgedb/pull/6723.

I'll stick this into the todo list for now, but PRs welcome if you want to take a swing at it!

**Comment by MiroslavPetrik** [comment]
@scotttrinh I've opened a PR. Would appreciate a review, as the params extraction for OR case is not possible, so I had to nest try catch, but its ordered, but maybe it could be split into 2 separate actions instead. :)
