### ISSUE TITLE
Add documentation for `@edgedb/create`

### ISSUE THREAD

**Issue by scotttrinh** [edgedb/edgedb-js#848]
Include some details about:

- We typically try to duplicate the canonical "create-app" template for the various frameworks
- We plan to track major changes to the upstream create-app
- We attempt to support the major options when it comes to the upstream create-apps, but cannot always support every possible permutation
- If you do not have the EdgeDB CLI installed, we attempt to install it for you using our typical installation procedure.

**Comment by beerose** [comment]
Closed in https://github.com/edgedb/edgedb-js/pull/849
