### ISSUE TITLE
[QUESTION]: is edgedb-js compatible with Deno?

### ISSUE THREAD

**Issue by shackra** [edgedb/edgedb-js#88]
[Deno](https://deno.land/) is _"a simple, modern and secure runtime for JavaScript and TypeScript that uses V8 and is built in Rust."_ since this is the only edgedb client for a typed language I know, I was wondering if this package is compatible with Deno, [some clues](https://stackoverflow.com/a/61821141/2020214):

- this package does not use [non-polyfilled Node.js APIs](https://github.com/denoland/deno_std/tree/main/node#supported-builtins), or 
- this package can be imported with `https://jspm.io/`.

**Comment by 1st1** [comment]
We plan to add deno support soon!
