### ISSUE TITLE
Queries generator inference error query instead queryRequiredSingle

### ISSUE THREAD

**Issue by ethras** [edgedb/edgedb-js#930]
**Describe the bug**
The Queries Generator is generating incorrect TypeScript code for my EdgeQL query. 

Instead of using queryRequiredSingle for queries that are expected to return a single result, it's using query. This discrepancy leads to potential runtime errors when the query is executed, as the generated function does not enforce the single result expectation.

**Reproduction**
```
// EdgeQL query
select Event {startTime}
 filter .id = <uuid>$eventId

// Then
npx @edgedb/generate queries --file src/edgeql-js/queries

```

```typescript
// Generated TypeScript code
export function test(client: Executor, args: TestArgs): Promise<TestReturns> {
 return client.query(`\
select Event {startTime}
 filter .id = <uuid>$eventId`, args);
}

/*
 TS error : Type 'Promise<unknown[]>' is not assignable to type 'Promise<TestReturns>'.
  Property '"startTime"' is missing in type 'unknown[]' but required in type '{ startTime: Date; }'.ts(2322)
/* 

// Expected TypeScript code
export function test(client: Executor, args: TestArgs): Promise<TestReturns> {
 return client.queryRequiredSingle(`\
select Event {startTime}
 filter .id = <uuid>$eventId`, args);
}

```

**Expected behavior**
The generated TypeScript code should use queryRequiredSingle for queries that are expected to return a single result, ensuring type safety and preventing runtime errors due to unexpected query results.

**Versions :**

- OS: MacoS Sonoma
- EdgeDB version: 4.7
- EdgeDB CLI version: EdgeDB CLI 4.0.0-alpha.1+ddfbe70
- `@edgedb/generate` version : 0.5.0-canary.20240325T144955
- Node/Deno version: v18.17.1

**Comment by scotttrinh** [comment]
This is working as intended since that query does not throw if it doesn't find an object with that ID, it returns null instead. If you want the query to fail with a database error you could wrap that query in an `assert_exists` which will cause the query cardinality to be exactly one, which seems like the behavior you are expecting here.

**Comment by scotttrinh** [comment]
Oh actually the cardinality seems like it is wrong in your example, it should be using `querySingle`. Are you sure the query you are testing is filtering on exclusive property like in your example code above?

**Comment by ethras** [comment]
> Oh actually the cardinality seems like it is wrong in your example, it should be using `querySingle`. Are you sure the query you are testing is filtering on exclusive property like in your example code above?

Yes, it was working fine before I upgraded to canary from the latest version 0.4.1

**Comment by scotttrinh** [comment]
Is your `TestReturns` type correctly typed as `| null`? When I run this on `master`, I get the following:

```ts
export type ExclusiveArgs = Readonly<{
  "id": string;
}>;

export type ExclusiveReturns = {
  "name": string;
  "id": string;
  "number_of_movies": number | null;
  "secret_identity": string | null;
  "height": string | null;
} | null;

export function exclusive(client: Executor, args: ExclusiveArgs): Promise<ExclusiveReturns> {
  return client.query(`\
select Hero {*} filter .id = <uuid>$id;`, args);

}
```

Which is correct for the types, although it isn't using `querySingle` (I'll look into that).

**Comment by ethras** [comment]
![CleanShot 2024-04-01 at 01 07 21@2x](https://github.com/edgedb/edgedb-js/assets/17152220/13d0c108-ca56-4f12-ac2d-aa13dc114fc3)
Yes it's correctly typed but typescript complains

**Comment by scotttrinh** [comment]
Thanks for the report! We've been iterating on these, so I'll make sure we have test coverage here once we get it fixed.

**Comment by scotttrinh** [comment]
Looks like this is a misalignment of canary versions of the driver (which defines the introspection queries) and the generate module. See if you can update to the latest canary on both the driver package (`edgedb`) and the generator package (`@edgedb/generate`) and get it working. I've added some tests in a separate PR that ensures we don't break this again in the future.
