### ISSUE TITLE
In auth helper libraries, cookies have a session expiration time instead of living as long as the token itself

### ISSUE THREAD

**Issue by scotttrinh** [edgedb/edgedb-js#990]
If you do not specify an expiration, the cookie will expire at the end of the browser session (ie when the browser is closed). However, the browser I primarily use to test has a session-restore feature which has always restored the session cookie when the browser restarts so I've never noticed this behavior.

We should expire the cookie when the session token itself is set to expire.

**Comment by patrikengborg** [comment]
This is still an issue for oauth in the auth-sveltekit lib, possibly in the other helper libs as well?
cookies.set… (without the expires option) are still used in some places. I guess the setVerifierCookie and setAuthCookie functions should be used exclusively.
I can submit a PR for auth-sveltekit, not sure about the other libs though.

**Comment by scotttrinh** [comment]
Ahh, I think the isssue here is that we just haven't done a round of releases to the `latest` tag for some of the auth libraries. Will fix. In the meantime, feel free to test out a canary and see if it is working for you: `@edgedb/auth-sveltekit@canary`.

**Comment by scotttrinh** [comment]
@patrikengborg But if you see any cookies being set without an expiration in any of the auth libraries, PRs or issues very welcome!

**Comment by patrikengborg** [comment]
Yes, canary works, it uses the token_time_to_live setting now. Great!
edgedb-pkce-verifier is a session cookie though, but maybe that's how it's supposed to be?

**Comment by scotttrinh** [comment]
@patrikengborg 
Hmmm. It should be set to an explicit 7 days: https://github.com/edgedb/edgedb-js/blob/c63404d52bc888bbc74808686d46184bf29ca0f3/packages/auth-sveltekit/src/server.ts#L124

Maybe you're seeing an older cookie? Can you try clearing your cookies, and starting a new session and see if it's still not being set? If it's not, let's open a new issue and investigate.
